name: Bug Report
description: Report a bug or unexpected behavior in DocAnvil
title: "[Bug]: "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide as much detail as possible.

  - type: input
    id: version
    attributes:
      label: DocAnvil Version
      description: What version are you using?
      placeholder: "e.g. 0.1.4"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      placeholder: "e.g. macOS 14, Ubuntu 22.04, Windows 11"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of the problem.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide exact steps to reproduce the issue.
      placeholder: |
        1. Run command...
        2. Build documentation...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Output / Logs
      description: Paste any relevant logs or error messages.
      render: shell
    validations:
      required: false
