name: Feature Proposal
description: Propose a new feature for DocAnvil
title: "[Feature]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for your proposal!

        Before submitting a feature request:
        - Ensure it aligns with DocAnvil's philosophy (minimal input, beautiful output).
        - Consider whether this belongs in core or as a plugin.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve?
      placeholder: Describe the user pain point.
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Describe the feature you would like to see.
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: Where do you believe this belongs?
      options:
        - Core
        - Plugin
        - Unsure
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered other approaches?
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Mockups, examples, or references.
      required: false
