[[nav]]
page = "index"
label = "Accueil"

[[nav]]
separator = "Guides"

[[nav]]
autodiscover = "guides"

[[nav]]
separator = true

[[nav]]
separator = "Rédaction"

[[nav]]
autodiscover = "writing"

[[nav]]
separator = "Référence"

[[nav]]
autodiscover = "reference"

[[nav]]
separator = true

[[nav]]
separator = "Déploiement"

[[nav]]
autodiscover = "deployment"

[[nav]]
label = "Développement"
autodiscover = "development"
